# Install Timesketch on Ubuntu Docker images using GIFT PPA
name: test_install_timesketch
on: [push]
jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['18.04', '20.04']
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
    - name: Set up container
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update -q
        apt-get install -y libterm-readline-gnu-perl locales software-properties-common
        locale-gen en_US.UTF-8
        ln -f -s /usr/share/zoneinfo/UTC /etc/localtime
    - name: Install Timesketch
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        TRACK=`echo ${GITHUB_REF} | sed 's?^.*/??;s?master?stable?'`;
        add-apt-repository -y ppa:gift/${TRACK}
        apt-get update -q
        apt-get install -y python3-timesketch
